#!/usr/bin/env bash

cd ~
mkdir gcp-training-repositories
cd gcp-training-repositories
mkdir day-1
mkdir day-2
mkdir day-3

cd day-1
hub clone armakuni/python-lab-bowling-game
hub clone armakuni/python-lab-doorbell
hub clone armakuni/python-lab-bdd
cd ..

cd day-2
hub clone armakuni/gcp-training-intro-to-cloudrun
cd gcp-training-intro-to-cloudrun
hub fork --remote-name origin
cd ../..

cd day-3
hub clone armakuni/gcp-training-customer-service
cd gcp-training-customer-service
hub fork --remote-name origin
cd ..

hub clone armakuni/gcp-training-account-service
cd gcp-training-account-service
hub fork --remote-name origin
cd ..

hub clone armakuni/gcp-training-transaction-service
cd gcp-training-transaction-service
hub fork --remote-name origin
cd ..

hub clone armakuni/gcp-training-balance-service
cd gcp-training-balance-service
hub fork --remote-name origin
cd ..

hub clone armakuni/gcp-training-cashier-service
cd gcp-training-cashier-service
hub fork --remote-name origin
cd ..

hub clone armakuni/gcp-training-microservices-infrastructure
cd gcp-training-microservices-infrastructure
hub fork --remote-name origin
cd ../..

hub clone armakuni/gcp-training-microservices-smoke-test
cd gcp-training-microservices-smoke-test
hub fork --remote-name origin
cd ../..