#!/usr/bin/env bash

hub delete python-lab-bowling-game --yes
hub delete python-lab-doorbell --yes
hub delete python-lab-bdd --yes
hub delete gcp-training-intro-to-cloudrun --yes
hub delete gcp-training-customer-service --yes
hub delete gcp-training-account-service --yes
hub delete gcp-training-transaction-service --yes
hub delete gcp-training-balance-service --yes
hub delete gcp-training-cashier-service --yes
hub delete gcp-training-microservices-infrastructure --yes
hub delete gcp-training-microservices-smoke-test --yes

rm -rf ~/gcp-training-repositories
